### PR TITLE
Fix typo in last commit (negate condition).

### PR DESCRIPTION
**Pull request by MichaelGrupp**

### CODE REVIEW

**Comment by cschuet** [comment]
@wally-the-cartographer Oh, my. I think it is time for me to stop working for the day :)

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by MichaelGrupp** [comment]
Haha, same here - classic "let me finish one more small thing before I leave".

**Pull request merged**
