### PR TITLE
Move 'finished' getter to the base class.

### PR DESCRIPTION
**Pull request by pifon2a**
Just a small refactoring.

### CODE REVIEW

**Comment by cschuet** [comment]
@pifon2a Please fix test errors.

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 3.

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> handle work item: PR 803 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at 3660408 Forward declare unique_ptr<LocalSlamResultData> (#824)
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
From https://github.com/googlecartographer/cartographer
   3660408..31ec896  master     -> origin/master
Updating 3660408..31ec896
Fast-forward
 cartographer/mapping/map_builder.cc     |  3 ++-
 cartographer/mapping/submaps.h          |  3 ++-
 cartographer/mapping_2d/submaps.cc      |  7 +++++--
 cartographer/mapping_2d/submaps.h       |  3 ++-
 cartographer/mapping_2d/submaps_test.cc |  2 +-
 cartographer/mapping_3d/submaps.cc      | 13 ++++++++-----
 cartographer/mapping_3d/submaps.h       |  3 ++-
 cartographer/mapping_3d/submaps_test.cc |  2 +-
 8 files changed, 23 insertions(+), 13 deletions(-)
Current branch master is up to date.
 => Checking out pifon2a/new_nit as local branch pr_803.
 $ git remote add pifon2a git@github.com:pifon2a/cartographer.git [data/cartographer]
fatal: remote pifon2a already exists.
 $ git fetch pifon2a [data/cartographer]
 $ git branch --track pr_803 pifon2a/new_nit [data/cartographer]
Branch 'pr_803' set up to track remote branch 'new_nit' from 'pifon2a' by rebasing.
 => Switching to branch pr_803.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at 31ec896 Add parameter to Submap::ToProto() to determine whether to include loop (#821)
 $ git clean -fd [data/cartographer]
 $ git checkout pr_803 [data/cartographer]
Switched to branch 'pr_803'
Your branch is up to date with 'pifon2a/new_nit'.
 $ git pull --force [data/cartographer]
Already up to date.
Current branch pr_803 is up to date.
 => merge master.
 $ git merge master [data/cartographer]
Auto-merging cartographer/mapping_3d/submaps.h
Auto-merging cartographer/mapping_3d/submaps.cc
CONFLICT (content): Merge conflict in cartographer/mapping_3d/submaps.cc
Auto-merging cartographer/mapping_2d/submaps.h
Auto-merging cartographer/mapping_2d/submaps.cc
CONFLICT (content): Merge conflict in cartographer/mapping_2d/submaps.cc
Auto-merging cartographer/mapping/submaps.h
Automatic merge failed; fix conflicts and then commit the result.
 => Abandoning branch pr_803.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at a7bbf72 Ran clang-format.
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_803 [data/cartographer]
Deleted branch pr_803 (was a7bbf72).

~~~

**Pull request merged**
