### PR TITLE
Fix debug build

### PR DESCRIPTION
**Pull request by ojura**
Similar to #418.

### CODE REVIEW

**Comment by gaschler** [comment]
Is this change enough fix the GCC debug build?
A quick grep shows 8 places where `LOG(FATAL);` is used.
(In case you are about the change all 8 places, I'd rather not add a comment everywhere.)

**Comment by ojura** [comment]
No, it's not required everywhere. See discussion in #418 (only if nontrivial destructor runs after `LOG(FATAL`).

**Comment by gaschler** [comment]
Thanks, this will also fix my local valgrind runs.

@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 3.

**Pull request merged**
