### PR TITLE
Added cartographer test library to CMake project

### LINKED ISSUE #1128: Build broken on systems which do not have gtest header in standard path
Opening a separate issue for this, because I believe it to be of high importance. See https://github.com/googlecartographer/cartographer/pull/1101#discussion_r184844641.

### PR DESCRIPTION
**Pull request by schwoere**
Fake, mock and test helpers are now compiled into a test library.

This should resolve #1128. The bazel build file was updated in #1101.

### CODE REVIEW

**Comment by schwoere** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user schwoere. Merge queue now has a length of 1.

**Comment by ojura** [comment]
Thanks for the quick fix!

**Comment by kdaun** [comment]
@schwoere PTAL. It seems like your forgot the follow up change in `cartographer_ros`. 
https://travis-ci.org/googlecartographer/cartographer_ros/builds/373162785?utm_source=email&utm_medium=notification

**Comment by schwoere** [comment]
@kdaun Thanks for letting me know. I fixed the cmake file and cartographer_ros is building now again.

**Pull request merged**
