### PR TITLE
Test MapBuilderServer

### PR DESCRIPTION
**Pull request by gaschler**
Test to start and stop the MapBuilderServer.
Moves test helper functions in common with MapBuilderTest
to internal/mapping.

### CODE REVIEW

**Comment by gaschler** [comment]
This test reveals that the slam thread does not shut down and fix #763 is necessary and should be merged before this.

**Comment by gaschler** [comment]
@cschuet This is now ready to review and merge.

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 2.

**Pull request merged**
