### PR TITLE
Add sparse Eigen support to Bazel build.

### PR DESCRIPTION
**Pull request by cschuet**

### CODE REVIEW

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by ojura** [comment]
Is EigenSparse as fast for you as SuiteSparse? IIRC I got slow performance as soon as I forgot to install SuiteSparse, even with EigenSparse.

**Comment by cschuet** [comment]
@ojura The problem with SuiteSparse is that is extremely difficult to make a hermetic Bazel build for it. That's why I put in Eigen sparse for now to get away from DENSE_QR which is super super slow.

**Pull request merged**
