### PR TITLE
Introduce common::ToSeconds for std::chrono::steady_clock::duration.

### PR DESCRIPTION
**Pull request by CodeArno**
Introduce a new overload of ToSeconds for std::chrono::steady_clock and use it for the work queue delay metric.

### CODE REVIEW

**Comment by CodeArno** [comment]
@wohe @spielawa PTAL

**Comment by CodeArno** [comment]
@wohe Can you please ask Wally to merge?

**Comment by wohe** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user wohe. Merge queue now has a length of 5.

**Comment by wohe** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user wohe. Merge queue now has a length of 1.

**Pull request merged**
