### PR TITLE
Miscellaneous: rename odometer->odometry

### PR DESCRIPTION
**Pull request by ojura**
Since we're adding `sensor::OdometryData`, I think that the function should be called `AddOdometryData`.

### CODE REVIEW

**Comment by gaschler** [comment]
To me, the rename sounds good. (The style of the PR would still need to be corrected, but let's first decide if we do the rename.)

**Comment by ojura** [comment]
While we're here doing cleanup, do you want me to commit a clang-format on the complete Cartographer codebase? There's quite a few unformatted lines in some files which keep popping up when I run clang-format, so I have to get rid of them when staging my changes in git. It's quite annoying.

**Comment by SirVer** [comment]
> (The style of the PR would still need to be corrected, but let's first decide if we do the rename.)

Wally runs clang-format, so should be all good. 

> While we're here doing cleanup, do you want me to commit a clang-format of the complete Cartographer codebase?

No. clang-format is not consistent between different versions, so your clang-format will modify differently. With the mergebot, we never need to see the changes (since the formatting happens after the code review) and the code base will stay in shape.

I think the rename is a good thing, but you missed a few cases, at least SparsePoseGraph and OptimizationProblem in 2d and 3d.

**Comment by ojura** [comment]
I renamed the other occurences as well.

**Comment by SirVer** [comment]
We discussed this a bit internally and there was a reason behind the name and we want to keep it in places. Where we are taking a sensor::OdometryData, the rename makes sense - and that is most places. However, on the outer most layer

On the very outer layer though in `trajectory_builder.h` there is no mention of OdometryData and we want to emphasize that we are adding independent observations from different sensors there. This will become part of the public API too, so it is important to be consistent there: `Add<Sensor>Data`. So `AddOdometerData` is correct there. I made this change to this branch and made sure it still compiles. Conveniently, this makes googlecartographer/cartographer_ros#592 unnecessary.

@ojura D'accord?

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Error: PUT https://api.github.com/repos/googlecartographer/cartographer/pulls/665/merge: 405 At least one approved review is required by reviewers with write access. []

Log:
~~~
=> Rebasing PR 665 on googlecartographer/cartographer onto master.
=> Switching to branch master.
 $ git rebase --abort [data/cartographer]
No rebase in progress?
 $ git checkout -f [data/cartographer]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
Already up to date.
 $ git remote add larics git@github.com:larics/cartographer.git [data/cartographer]
fatal: remote larics already exists.
 $ git fetch larics [data/cartographer]
 $ git branch --track pr_665 larics/rename-odometry [data/cartographer]
Branch 'pr_665' set up to track remote branch 'rename-odometry' from 'larics'.
=> Switching to branch pr_665.
 $ git rebase --abort [data/cartographer]
No rebase in progress?
 $ git checkout -f [data/cartographer]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer]
 $ git checkout pr_665 [data/cartographer]
Switched to branch 'pr_665'
Your branch is up to date with 'larics/rename-odometry'.
 $ git pull --force [data/cartographer]
Already up to date.
 $ git rebase master [data/cartographer]
Current branch pr_665 is up to date.
=> Running clang-format on all *.cc and *.h files [data/cartographer]
 $ git commit -am Ran clang-format. [data/cartographer]
On branch pr_665
Your branch is up to date with 'larics/rename-odometry'.

nothing to commit, working tree clean
 $ git push --force larics HEAD:rename-odometry [data/cartographer]
Everything up-to-date
=> Abandoning branch pr_665.
=> Switching to branch master.
 $ git rebase --abort [data/cartographer]
No rebase in progress?
 $ git checkout -f [data/cartographer]
Your branch is up to date with 'larics/rename-odometry'.
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_665 [data/cartographer]
Deleted branch pr_665 (was ed79792).

~~~

**Comment by ojura** [comment]
@SirVer you forgot to approve the PR :-)

**Comment by SirVer** [comment]
I did :). Good that we tested that though, I wasn't sure if that works.

@ojura to test one more thing, could you ask wally to merge? Theoretically it should not work, since you are not in the right group. But this was untested so far.

**Comment by ojura** [comment]
Sure.

@wally-the-cartographer merge

**Comment by SirVer** [comment]
Cool, it is working. Thanks!

@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 2.

**Comment by ojura** [comment]
Great. #666 got queued for merging earlier than this one though, so I'll have to update this one to also include the rename of one additional `AddOdometerData` that was introduced there.

**Comment by ojura** [comment]
@SirVer this might be a good opportunity to test what happens when I push after you approve and test merging.

**Comment by wally-the-cartographer** [comment]
Error: exit status 128

Log:
~~~
=> Rebasing PR 665 on googlecartographer/cartographer onto master.
=> Switching to branch master.
 $ git rebase --abort [data/cartographer]
No rebase in progress?
 $ git checkout -f [data/cartographer]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
From https://github.com/googlecartographer/cartographer
   a7680f6..5496cbd  master     -> origin/master
Updating a7680f6..5496cbd
Fast-forward
 cartographer/mapping/map_builder.cc                  | 20 ++++++++++++++++++--
 cartographer/mapping/proto/serialization.proto       |  8 +++++++-
 cartographer/mapping/sparse_pose_graph.h             |  8 ++++++++
 cartographer/mapping_2d/sparse_pose_graph.cc         |  5 +++++
 cartographer/mapping_2d/sparse_pose_graph.h          |  5 ++++-
 .../sparse_pose_graph/optimization_problem.cc        |  5 +++++
 .../sparse_pose_graph/optimization_problem.h         |  1 +
 cartographer/mapping_3d/sparse_pose_graph.cc         |  5 +++++
 cartographer/mapping_3d/sparse_pose_graph.h          |  5 ++++-
 .../sparse_pose_graph/optimization_problem.cc        |  5 +++++
 .../sparse_pose_graph/optimization_problem.h         |  1 +
 11 files changed, 63 insertions(+), 5 deletions(-)
 $ git remote add larics git@github.com:larics/cartographer.git [data/cartographer]
fatal: remote larics already exists.
 $ git fetch larics [data/cartographer]
 $ git branch --track pr_665 larics/rename-odometry [data/cartographer]
Branch 'pr_665' set up to track remote branch 'rename-odometry' from 'larics'.
=> Switching to branch pr_665.
 $ git rebase --abort [data/cartographer]
No rebase in progress?
 $ git checkout -f [data/cartographer]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer]
 $ git checkout pr_665 [data/cartographer]
Switched to branch 'pr_665'
Your branch is up to date with 'larics/rename-odometry'.
 $ git pull --force [data/cartographer]
Already up to date.
 $ git rebase master [data/cartographer]
First, rewinding head to replay your work on top of it...
Applying: Serialize odometry data.
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
M	cartographer/mapping/map_builder.cc
M	cartographer/mapping/proto/serialization.proto
M	cartographer/mapping/sparse_pose_graph.h
M	cartographer/mapping_2d/sparse_pose_graph.cc
M	cartographer/mapping_2d/sparse_pose_graph.h
M	cartographer/mapping_2d/sparse_pose_graph/optimization_problem.cc
M	cartographer/mapping_2d/sparse_pose_graph/optimization_problem.h
M	cartographer/mapping_3d/sparse_pose_graph.cc
M	cartographer/mapping_3d/sparse_pose_graph.h
M	cartographer/mapping_3d/sparse_pose_graph/optimization_problem.cc
M	cartographer/mapping_3d/sparse_pose_graph/optimization_problem.h
Falling back to patching base and 3-way merge...
Auto-merging cartographer/mapping_3d/sparse_pose_graph/optimization_problem.cc
CONFLICT (content): Merge conflict in cartographer/mapping_3d/sparse_pose_graph/optimization_problem.cc
Auto-merging cartographer/mapping_3d/sparse_pose_graph.h
CONFLICT (content): Merge conflict in cartographer/mapping_3d/sparse_pose_graph.h
Auto-merging cartographer/mapping_2d/sparse_pose_graph/optimization_problem.cc
CONFLICT (content): Merge conflict in cartographer/mapping_2d/sparse_pose_graph/optimization_problem.cc
Auto-merging cartographer/mapping_2d/sparse_pose_graph.h
CONFLICT (content): Merge conflict in cartographer/mapping_2d/sparse_pose_graph.h
Auto-merging cartographer/mapping/proto/serialization.proto
CONFLICT (content): Merge conflict in cartographer/mapping/proto/serialization.proto
Auto-merging cartographer/mapping/map_builder.cc
CONFLICT (content): Merge conflict in cartographer/mapping/map_builder.cc
Patch failed at 0001 Serialize odometry data.
The copy of the patch that failed is found in: .git/rebase-apply/patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

=> Abandoning branch pr_665.
=> Switching to branch master.
 $ git rebase --abort [data/cartographer]
 $ git checkout -f [data/cartographer]
Your branch is up to date with 'larics/rename-odometry'.
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_665 [data/cartographer]
Deleted branch pr_665 (was 15df7d8).

~~~

**Comment by ojura** [comment]
Seems like I could insert malicious content and Wally would have merged it :-) Although I could not prevent the merge conflict in any way.

Anyhow, @SirVer  can you please retrigger merging? The conflict with #666 has been fixed.

**Comment by SirVer** [comment]
> Seems like I could insert malicious content and Wally would have merged it :-)

Yes, that is true. I think the mergebot should work on SHAs instead of remote branches, but as I explained in another PR that would mean that GitHub would never mark PRs as merged - only as closed.

@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by ojura** [comment]
> Yes, that is true. I think the mergebot should work on SHAs instead of remote branches, but as I explained in another PR that would mean that GitHub would never mark PRs as merged - only as closed.

I was thinking something more like recording the SHA of the remote branch in the moment you issue
`@wally-the-cartographer merge`. When Wally reaches the PR in the, it aborts if there's a mismatch.

You could also inconvenience yourself a bit by specifying the SHA manually in the merge command. E.g. for this PR you would do  `@wally-the-cartographer merge 22ba8fc`.

**Comment by SirVer** [comment]
> @wally-the-cartographer merge. When Wally reaches the PR in the queue, it aborts if there's a mismatch.

Year, there is a [TODO for that](https://github.com/googlecartographer/infrastructure/blob/master/wally_the_cartographer/cmd/root.go#L316) :). Unlikely I'll git this done till I leave Google at the end of this week though.

**Pull request merged**
