### PR TITLE
Add IsTrajectoryFrozen to PoseGraph interface

### PR DESCRIPTION
**Pull request by kdaun**
Adds IsTrajectoryFrozen to the PoseGraph interface

### CODE REVIEW

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Pull request merged**
