### PR TITLE
LoadState(FromFile) endpoints

### PR DESCRIPTION
**Pull request by gaschler**
[RFC=0023](https://github.com/googlecartographer/rfcs/blob/master/text/0023-delete-load.md)

### CODE REVIEW

**Comment by cschuet** [comment]
@gaschler Can you update client_server_test.cc?

**Comment by gaschler** [comment]
Done, added test coverage for the trajectory remapping return value.

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Pull request merged**
