### PR TITLE
Unwarp by point in LocalTrajectoryBuilder.

### PR DESCRIPTION
**Pull request by gaschler**

### CODE REVIEW

**Comment by gaschler** [comment]
This changes depends on https://github.com/googlecartographer/cartographer_ros/pull/576

**Comment by gaschler** [comment]
I did some measurements and the computation time of 3D SLAM was ~40% longer, so do not merge the current implementation yet.

**Comment by SirVer** [comment]
Oh right, I forgot. Should this PR then be closed till it is ready?

**Comment by gaschler** [comment]
Closing because the current implementation is not efficient enough in 3D.

**Comment by gaschler** [comment]
With some coarse filtering before unwarping in the 3D pipeline, this feature is now a better compromise between correct point cloud unwarping and computation time. In the worst case, computation time is ~20% longer for offline SLAM on the data of two high-density 3D laser scanners.

**Comment by cschuet** [comment]
@wohe Do you feel the performance impact is acceptable? Should we go ahead with this feature?

**Comment by cschuet** [comment]
@wohe How about disabling unwarping if all points in the batch have the same timestamp?

**Comment by gaschler** [comment]
I implemented the TODO in ExtrapolatePose to cache the result there, which reduces the most common case (points without time deltas) to 100-105% computation time on frondend-heavy tasks (short offline mapping of high-density 3D data).
@cschuet Could you please take another look?

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 2.

**Comment by wohe** [comment]
@gaschler Should the comment at https://github.com/googlecartographer/cartographer/blob/0156e6b8ce3132786fb49c5a19cf0a9b95455842/cartographer/sensor/point_cloud.h#L36 be updated or do I misunderstand this change?

**Comment by gaschler** [comment]
@wohe Thanks for pointing out this wrong comment, sent you a PR.

**Pull request merged**
