### PR TITLE
Remove "_internal" from the metric family names.

### PR DESCRIPTION
**Pull request by CodeArno**
As discussed and requested in #1218, this PR removes the substring "_internal" from all the metric family names.

### CODE REVIEW

**Comment by CodeArno** [comment]
@wohe @gaschler PTAL

**Comment by wohe** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user wohe. Merge queue now has a length of 3.

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user wohe. Merge queue now has a length of 3.

**Pull request merged**
