### PR TITLE
Better Abseil library order

### PR DESCRIPTION
**Pull request by amikholap**
Got linker error for Abseil in the build env due to imprecise library order.
Worked fine on the dev machine though.
Maybe helps someone.

https://pastebin.com/raw/AEKPBt1n

### CODE REVIEW

**Comment by amikholap** [comment]
> Thanks, your CLA has been submitted.

**Comment by ojura** [comment]
Can we please merge #1387 instead until Abseil learns `make install`? It completely eliminates the ugliness of having to manually enumerate Abseil libraries.

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 2.

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> handle work item: PR 1458 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at aaa8a9a6 Configurable CC/CXX compiler toolchain in Dockerfiles. (#1402)
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
From https://github.com/googlecartographer/cartographer
   aaa8a9a6..b7fb299d  master     -> origin/master
Updating aaa8a9a6..b7fb299d
Fast-forward
 cartographer/io/probability_grid_points_processor.cc | 17 +++++++++--------
 cmake/modules/FindAbseil.cmake                       |  2 +-
 2 files changed, 10 insertions(+), 9 deletions(-)
 => Checking out amikholap/better-abseil-library-order as local branch pr_1458.
 $ git remote add amikholap git@github.com:amikholap/cartographer.git [data/cartographer]
fatal: remote amikholap already exists.
 $ git fetch amikholap [data/cartographer]
 $ git branch --track pr_1458 amikholap/better-abseil-library-order [data/cartographer]
Branch 'pr_1458' set up to track remote branch 'better-abseil-library-order' from 'amikholap'.
 => Switching to branch pr_1458.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at b7fb299d Better Abseil library order (#1458)
 $ git clean -fd [data/cartographer]
 $ git checkout pr_1458 [data/cartographer]
Switched to branch 'pr_1458'
Your branch is up to date with 'amikholap/better-abseil-library-order'.
 $ git pull --force [data/cartographer]
Already up to date.
 => merge master.
 $ git merge master [data/cartographer]
Merge made by the 'recursive' strategy.
 => Running clang-format on all *.cc and *.h files
 $ git commit -am Ran clang-format. [data/cartographer]
On branch pr_1458
Your branch is ahead of 'amikholap/better-abseil-library-order' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
 $ git push --force amikholap HEAD:better-abseil-library-order [data/cartographer]
To github.com:amikholap/cartographer.git
 ! [remote rejected]   HEAD -> better-abseil-library-order (permission denied)
error: failed to push some refs to 'git@github.com:amikholap/cartographer.git'
 => Abandoning branch pr_1458.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at b4c82682 Merge branch 'master' into pr_1458
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_1458 [data/cartographer]
Deleted branch pr_1458 (was b4c82682).

~~~

**Pull request merged**
