### PR TITLE
Fix unused lambda capture warning

### PR DESCRIPTION
**Pull request by damienrg**
- [ X] Keep your PR rebased to master.
- [ X] Keep your PR under 200 lines of code and address a single concern.
- [ X] Add unit test(s) and documentation (these do not count toward your 200 lines).
- [ X] Adhere to the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html).
- [ X] Run `clang-format -style=Google` on your code (this alone is not enough to ensure you've followed the style guide).
- [ X] Run `ninja test` or `catkin_make_isolated --install --use-ninja --pkg cartographer --make-args test` as appropriate.

### CODE REVIEW

**Comment by SirVer** [comment]
nice, thank you!

@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by ojura** [comment]
@damienrg you might want to change the PR message to something more informative, as it gets pasted into the merge commit description by the bot.

**Comment by SirVer** [comment]
@ojura @damienrg That was on me. I should have edited that before merging. Sorry :(

**Pull request merged**
