### PR TITLE
Test TrajectoryBuilderStub

### PR DESCRIPTION
**Pull request by gaschler**

### CODE REVIEW

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 2.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by cschuet** [comment]
Test fails with

~~~
[ RUN      ] ClientServerTest.LocalSlam2D
I1220 15:51:47.954144  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/map_builder_server.lua' for 'map_builder_server.lua'.
I1220 15:51:47.954161  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/map_builder_server.lua' for 'map_builder_server.lua'.
I1220 15:51:47.954201  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
I1220 15:51:47.954212  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
I1220 15:51:47.954249  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
I1220 15:51:47.954260  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
I1220 15:51:47.954573  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
I1220 15:51:47.954587  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
I1220 15:51:47.954620  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
I1220 15:51:47.954648  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
I1220 15:51:47.954732  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
I1220 15:51:47.954744  1392 configuration_file_resolver.cc:41] Found '/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
I1220 15:51:47.955180  1439 map_builder_server.cc:146] Starting SLAM thread.
I1220 15:51:47.956617  1440 submaps.cc:190] Added submap 1
I1220 15:51:47.957314  1439 ordered_multi_queue.cc:172] All sensor data for trajectory 0 is available starting at '123'.
W1220 15:51:47.957900  1439 pose_extrapolator.cc:168] Queue too short for velocity estimation. Queue duration: 0 ms

Optimizing: Done.     
I1220 15:51:47.959774  1434 constraint_builder.cc:261] 0 computations resulted in 0 additional constraints.
I1220 15:51:47.959784  1434 constraint_builder.cc:263] Score histogram:
Count: 0
W1220 15:51:47.964099  1439 ordered_multi_queue.cc:67] Ignored data for queue: '(0, range)'
../cartographer_grpc/client_server_test.cc:253: Failure
Value of: measurements.size()
  Actual: 40
Expected: local_slam_result_poses.size()
Which is: 6
../cartographer_grpc/client_server_test.cc:258: Failure
The difference between kTravelDistance and (local_slam_result_poses.back().translation() - local_slam_result_poses.front().translation()) .norm() is 1.0718862091404822, which exceeds 0.1 * kTravelDistance, where
kTravelDistance evaluates to 1.2,
(local_slam_result_poses.back().translation() - local_slam_result_poses.front().translation()) .norm() evaluates to 0.12811379085951774, and
0.1 * kTravelDistance evaluates to 0.12.
I1220 15:51:47.966583  1392 server.cc:158] Shutting down server.
I1220 15:51:47.966704  1392 completion_queue_thread.cc:40] Shutting down completion queue 0x120d160
I1220 15:51:47.966737  1392 event_queue_thread.cc:39] Shutting down event queue 0x120d790
I1220 15:51:48.066843  1392 server.cc:180] Shutdown complete.

Optimizing: Done.     
I1220 15:51:48.066977  1434 constraint_builder.cc:261] 0 computations resulted in 0 additional constraints.
I1220 15:51:48.066990  1434 constraint_builder.cc:263] Score histogram:
Count: 0
[  FAILED  ] ClientServerTest.LocalSlam2D (113 ms)
~~~

Thinking more about it this really is not all that surprising

1. `MapBuilderServer::WaitUntilIdle()` at most (I am not even sure of that) guarantees that all local SLAM results have been generated and enqueued into the send queues of the `ReceiveLocalSlamResult`-RPC object. By no means it guarantees that they have been delivered.
2. `FinishTrajectory` then removes the subscriptions and calls `Rpc::Finish()` which enqueues another item in the send queue.

Even if you are able to express that you want to wait until the server actually finished processing the event queue, there is no guarantee that the client thread was able to finish processing the server responses.

What I just tried is adding a `std::condition_variable` and `wait`ing for `measurements.size() == local_slam_results.size()`. If there is an actual bug the test should just time out. I ran the test in a loop for an hour on my machine and observed no flakiness anymore.

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Pull request merged**
