### PR TITLE
Glob only files in cartographer/

### PR DESCRIPTION
**Pull request by gaschler**
FIXES=#1044

### CODE REVIEW

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by gaschler** [comment]
Verified also for cartographer_ros' Indigo docker image.

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 2.

**Pull request merged**
