### PR TITLE
Add ground truth documentation.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
See [RFC 10](https://github.com/googlecartographer/rfcs/blob/master/text/0010-document-groundtruth-features.md)

[Rendered version](https://github.com/magazino/cartographer/blob/doc-groundtruth/docs/source/evaluation.rst)

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
Initial version, ready for your comments. The mention in the `cartographer_ros`tuning guide will follow afterwards.

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by MichaelGrupp** [comment]
Somehow the code blocks got lost on the web version. I did a local test build with Sphinx and it looked fine (screenshot) - but the ReadTheDocs version has some problems... any idea what is wrong so I can fix it?

[screenshot from 2018-02-01 18-59-27](https://user-images.githubusercontent.com/8985495/35694711-678d11c2-0782-11e8-956e-d8079316db34.png)

**Comment by MichaelGrupp** [comment]
--> see https://github.com/googlecartographer/cartographer/pull/883

**Comment by wohe** [comment]
LGTM

**Pull request merged**
