### PR TITLE
Skip constraint search against unfinished submaps.

### PR DESCRIPTION
**Pull request by gaschler**
The uplink server only receives the grid content of a submap after
that submap is finished for efficiency. Therefore, constraint
searches against that submap need to be skipped.
Also add checks to avoid this in the future.

FIXES=#1360

### CODE REVIEW

**Comment by gaschler** [comment]
@MichaelGrupp This should fix #1360, could you please verify?

**Comment by MichaelGrupp** [comment]
Will test.

**Comment by SirVer** [comment]
Defer to @wohe. Not doing SLAM anymore these days.

**Comment by gaschler** [comment]
@wohe Do you see any unexpected side effects on the constraint search when ignoring submaps with incomplete range data insertion? (I believe this didn't happen in single-process SLAM, so there shouldn't be side effects.)

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Pull request merged**
