### PR TITLE
Revert: Fix writing state of trajectories with unfinished submaps. #1286

### PR DESCRIPTION
**Pull request by cschuet**
Reason: Break rviz visualization for submaps loaded from pbstreams.

### CODE REVIEW

**Comment by schwoere** [comment]
Thanks for reverting.

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by MichaelGrupp** [comment]
Aaaaand this breaks cloud cartographer ;) 

Fix: https://github.com/googlecartographer/cartographer_ros/pull/966

I hope then everyone is happy.

**Pull request merged**
