### PR TITLE
Configurable CC/CXX compiler toolchain in Dockerfiles.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
Allows to build Docker images with Clang.

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
Todo: `-Wthread-safety` is not yet set as it seems?

**Comment by MichaelGrupp** [comment]
* can build using Clang and without libc++
* building with Clang and libc++ leads to ABI compatibility issues with Boost packages (and probably more)

**Comment by pifon2a** [comment]
@MichaelGrupp btw, boost packages can and should be removed from libcartographer. Only `boost//:iostreams` package is used to get gzip.

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by MichaelGrupp** [comment]
I set the default compiler for Travis builds to GCC again, Clang seems to be a bit brittle with some dependencies sometimes and I don't want to break the merge queue.

But we can leave the compiler option for testing.

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Pull request merged**
