### PR TITLE
Use efficient string concatenation

### PR DESCRIPTION
**Pull request by gaschler**
std::string::operator+ is very inefficient

### CODE REVIEW

**Comment by pifon2a** [comment]
Thanks for cleaning this up!

**Comment by gaschler** [comment]
Build depends on a fix in https://github.com/googlecartographer/cartographer/pull/1489

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Pull request merged**
