### PR TITLE
Fixing 846 without tests.

### PR DESCRIPTION
**Pull request by sotnik-github**
Fixing "Optimizing: -nan%... #846" https://github.com/googlecartographer/cartographer/issues/846.
The issue was triggered in a multithreaded execution, when all nodes were processed, but the working queue was still non empty (having other kind of jobs).
Unfortunately I failed to reproduce the bug in tests, so no new tests were added.

### CODE REVIEW

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 2.

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Error: exit status 128

Log:
~~~
=> handle work item: PR 1183 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at 691ec21a Merge branch 'master' into pr_1177
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
Already up to date.
 => Checking out sotnik-github/cartographer_bug_846 as local branch pr_1183.
 $ git remote add sotnik-github git@github.com:sotnik-github/cartographer.git [data/cartographer]
fatal: remote sotnik-github already exists.
 $ git fetch sotnik-github [data/cartographer]
 $ git branch --track pr_1183 sotnik-github/cartographer_bug_846 [data/cartographer]
fatal: A branch named 'pr_1183' already exists.

~~~

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Pull request merged**
