### PR TITLE
Implement WriteMapHandler.

### PR DESCRIPTION
**Pull request by cschuet**

### CODE REVIEW

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by cschuet** [comment]
@pifon2a As discussed test infra for gRPC framework coming :)

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 2.

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> handle work item: PR 851 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at edb1823  Add ProtoStreamWriterInterface and implement forwarding writer. (#849)
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
From https://github.com/googlecartographer/cartographer
   edb1823..1d2613c  master     -> origin/master
Updating edb1823..1d2613c
Fast-forward
 .../handlers/run_final_optimization.h              | 46 ++++++++++++++++++++++
 cartographer_grpc/map_builder_server.cc            |  4 ++
 cartographer_grpc/mapping/pose_graph_stub.cc       |  7 +++-
 cartographer_grpc/proto/map_builder_service.proto  |  4 ++
 4 files changed, 60 insertions(+), 1 deletion(-)
 create mode 100644 cartographer_grpc/handlers/run_final_optimization.h
 => Checking out cschuet/write_state as local branch pr_851.
 $ git remote add cschuet git@github.com:cschuet/cartographer.git [data/cartographer]
fatal: remote cschuet already exists.
 $ git fetch cschuet [data/cartographer]
 $ git branch --track pr_851 cschuet/write_state [data/cartographer]
Branch 'pr_851' set up to track remote branch 'write_state' from 'cschuet'.
 => Switching to branch pr_851.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at 1d2613c Add gRPC version of RunFinalOptimization(). (#852)
 $ git clean -fd [data/cartographer]
 $ git checkout pr_851 [data/cartographer]
Switched to branch 'pr_851'
Your branch is up to date with 'cschuet/write_state'.
 $ git pull --force [data/cartographer]
Already up to date.
 => merge master.
 $ git merge master [data/cartographer]
Auto-merging cartographer_grpc/proto/map_builder_service.proto
Auto-merging cartographer_grpc/map_builder_server.cc
CONFLICT (content): Merge conflict in cartographer_grpc/map_builder_server.cc
Automatic merge failed; fix conflicts and then commit the result.
 => Abandoning branch pr_851.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at 1e63edc Implement WriteMapHandler.
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_851 [data/cartographer]
Deleted branch pr_851 (was 1e63edc).

~~~

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Pull request merged**
