### PR TITLE
Adds a high level API for pose-relative landmarks

### PR DESCRIPTION
**Pull request by SirVer**
This is an compiling, but non-functional API proposal for #244.

### CODE REVIEW

**Comment by SirVer** [comment]
/cc @mofef, @jihoonl This is our suggestion for a public API for pose-relative constraints. This is just the API and no implementation. Do you think you can take this from here or do you require some pointers for the implementation?

Also, this is only tracking -> landmark. Landmark -> landmark would need to go into the SPA interface, but at our meeting it seemed sensible to start with this and see if you can model your problem in this frame of reference. Should this be infeasible, we can revisit the landmark -> landmark constraints again. Agreed?

/cc @macmason Has TRI an opinion on this?

**Comment by macmason** [comment]
LGTM.

**Comment by Mofef** [comment]
Thanks! To us this looks sufficient for now. I didn't find time to think about the detailed implementation yet, but it doesn't seam to be a very complex task. I will get back to you if I run into troubles.

**Comment by jihoonl** [comment]
Looks good to me too.

**Comment by SirVer** [comment]
This has bit rotted quite a bit and there is some agreement that this design is not sufficient. Closing for now as we have no immediate plans of implementing this.

If somebody wants to see this happen, please ping here or on the mailinglist again and we can start putting together a better design.

**Comment by timethy** [comment]
I'm very interested in tracking external landmarks (say, AR tags) to enhance submap construction but also for loop-closure purposes and think this would be of use to others, as well.
I'm aware of the work on fixed-frame constraints (e.g. GPS, VICON), however they do not help in tracking (initially unknown) identificable landmarks.
Maybe @SirVer could briefly explain me his ideas on how to implement it - or provide pointers.
I'm happy to contribute.

**Comment by SirVer** [comment]
Depending on what you want to achieve in detail, you might be good to go. Some tracking of map-fixed constraints has recently be added by @zjwoody. See the commits here: https://github.com/googlecartographer/cartographer/commits?author=zjwoody

**Comment by wohe** [comment]
FYI @pifon2a is looking into implementing this already.

**Comment by timethy** [comment]
Thanks for the pointers!

**Pull request closed without merging**
