### PR TITLE
Instrument metrics in local trajectory builders.

### PR DESCRIPTION
**Pull request by gaschler**
RFC=[0014](https://github.com/googlecartographer/rfcs/blob/master/text/0014-monitoring.md)

### CODE REVIEW

**Comment by gaschler** [comment]
So far, only the register methods are covered by cartographer_grpc.metrics.prometheus.metrics_test. What kind of test are you suggesting, extending the integration test in _grpc to actually record the metrics?

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Comment by pifon2a** [comment]
it was more of a joke :)

**Pull request merged**
