### PR TITLE
Ignore initial poses on gRPC server side.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
Fixes a crash if a client initializes with an initial pose inside a frozen map
that isn't known to the server.

### CODE REVIEW

**Comment by pifon2a** [comment]
please, fix `cartographer.cloud.internal.handlers.add_trajectory_handler_test`

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 7.

**Comment by MichaelGrupp** [comment]
@pifon2a "Verify pull request" blocks again

**Comment by pifon2a** [comment]
@MichaelGrupp pressed the button

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> handle work item: PR 1234 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at eff103f6 Ignore initial poses on gRPC server side. (#1234)
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
Already up to date.
Current branch master is up to date.
 => Checking out magazino/ignore-ini-pose as local branch pr_1234.
 $ git remote add magazino git@github.com:magazino/cartographer.git [data/cartographer]
fatal: remote magazino already exists.
 $ git fetch magazino [data/cartographer]
 $ git branch --track pr_1234 magazino/ignore-ini-pose [data/cartographer]
Branch 'pr_1234' set up to track remote branch 'ignore-ini-pose' from 'magazino'.
 => Switching to branch pr_1234.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at eff103f6 Ignore initial poses on gRPC server side. (#1234)
 $ git clean -fd [data/cartographer]
 $ git checkout pr_1234 [data/cartographer]
Switched to branch 'pr_1234'
Your branch is up to date with 'magazino/ignore-ini-pose'.
 $ git pull --force [data/cartographer]
Already up to date.
Current branch pr_1234 is up to date.
 => merge master.
 $ git merge master [data/cartographer]
Merge made by the 'recursive' strategy.
 => Running clang-format on all *.cc and *.h files
 $ git commit -am Ran clang-format. [data/cartographer]
On branch pr_1234
Your branch is ahead of 'magazino/ignore-ini-pose' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
 $ git push --force magazino HEAD:ignore-ini-pose [data/cartographer]
To github.com:magazino/cartographer.git
 ! [remote rejected]   HEAD -> ignore-ini-pose (permission denied)
error: failed to push some refs to 'git@github.com:magazino/cartographer.git'
 => Abandoning branch pr_1234.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at d2b0b430 Merge branch 'master' into pr_1234
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_1234 [data/cartographer]
Deleted branch pr_1234 (was d2b0b430).

~~~

**Pull request merged**
