### PR TITLE
Add slides from 171207.

### PR DESCRIPTION
**Pull request by cschuet**

### CODE REVIEW

**Comment by SirVer** [comment]
lgtm.

@wally-the-cartographer merge

**Comment by SirVer** [comment]
oh. for some reason I cannot lgtm this. Probably since I am no longer an owner.

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Error: PUT https://api.github.com/repos/googlecartographer/cartographer/pulls/753/merge: 405 At least one approved review is required by reviewers with write access. []

Log:
~~~
=> handle work item: PR 753 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at bf77b11 Implement gRPC data handlers and SLAM thread. (#749)
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
Already up to date.
Current branch master is up to date.
 => Checking out cschuet/slides as local branch pr_753.
 $ git remote add cschuet git@github.com:cschuet/cartographer.git [data/cartographer]
fatal: remote cschuet already exists.
 $ git fetch cschuet [data/cartographer]
 $ git branch --track pr_753 cschuet/slides [data/cartographer]
Branch 'pr_753' set up to track remote branch 'slides' from 'cschuet' by rebasing.
 => Switching to branch pr_753.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at bf77b11 Implement gRPC data handlers and SLAM thread. (#749)
 $ git clean -fd [data/cartographer]
 $ git checkout pr_753 [data/cartographer]
Switched to branch 'pr_753'
Your branch is up to date with 'cschuet/slides'.
 $ git pull --force [data/cartographer]
Already up to date.
Current branch pr_753 is up to date.
 => merge master.
 $ git merge master [data/cartographer]
Already up to date.
 => Running clang-format on all *.cc and *.h files
 $ git commit -am Ran clang-format. [data/cartographer]
On branch pr_753
Your branch is up to date with 'cschuet/slides'.

nothing to commit, working tree clean
 $ git push --force cschuet HEAD:slides [data/cartographer]
Everything up-to-date
 => Abandoning branch pr_753.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at fc52619 Merge branch 'master' into pr_753
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_753 [data/cartographer]
Deleted branch pr_753 (was fc52619).

~~~

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by SirVer** [comment]
@wally-the-cartographer merge

@cschuet I just tried again, but it seems wally is ignoring me. Could you investigate?

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
