### PR TITLE
(De)serialize trajectory data from the optimization problem

### PR DESCRIPTION
**Pull request by danielsievers**
* Write/Read the trajectory data (gravity, imu calibration, and fixed frame origin) into the serialized state proto

### CODE REVIEW

**Comment by danielsievers** [comment]
I signed it!

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by gaschler** [comment]
@danielsievers Please (force) push your changes again.
Unfortunately, our merge bot mixed it with other changes.

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
