### PR TITLE
Allow easier access to CeresPose's data_

### PR DESCRIPTION
**Pull request by RobertMilijas**
Allow easier modification of the optimization problem's variables by
introducing a `data()` getter, which returns a reference to `CeresPose::Data` contained inside the `CeresPose`. This allows setting the translation and rotation arrays using the assignment operator.

Also factor out conversion to `CeresPose::Data` into `FromPose()`, which transforms a `Rigid3d` pose into `CeresPose::Data`, similar to `FromPose` for 2D.

### CODE REVIEW

**Comment by RobertMilijas** [comment]
I signed it!

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Comment by RobertMilijas** [comment]
@pifon2a Hi, Wally's taking a long time. Is everything OK?

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> handle work item: PR 1149 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at d2453bc Update README.rst (#1144)
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
From https://github.com/googlecartographer/cartographer
   d2453bc..a0ec804  master     -> origin/master
Updating d2453bc..a0ec804
Fast-forward
 cartographer/mapping/internal/optimization/ceres_pose.cc | 15 +++++++++------
 cartographer/mapping/internal/optimization/ceres_pose.h  |  7 ++++++-
 2 files changed, 15 insertions(+), 7 deletions(-)
 => Checking out larics/ceres-pose-frompose as local branch pr_1149.
 $ git remote add larics git@github.com:larics/cartographer.git [data/cartographer]
fatal: remote larics already exists.
 $ git fetch larics [data/cartographer]
 $ git branch --track pr_1149 larics/ceres-pose-frompose [data/cartographer]
Branch 'pr_1149' set up to track remote branch 'ceres-pose-frompose' from 'larics'.
 => Switching to branch pr_1149.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at a0ec804 Allow easier access to CeresPose's data_ (#1149)
 $ git clean -fd [data/cartographer]
 $ git checkout pr_1149 [data/cartographer]
Switched to branch 'pr_1149'
Your branch is up to date with 'larics/ceres-pose-frompose'.
 $ git pull --force [data/cartographer]
Already up to date.
 => merge master.
 $ git merge master [data/cartographer]
Merge made by the 'recursive' strategy.
 => Running clang-format on all *.cc and *.h files
 $ git commit -am Ran clang-format. [data/cartographer]
On branch pr_1149
Your branch is ahead of 'larics/ceres-pose-frompose' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
 $ git push --force larics HEAD:ceres-pose-frompose [data/cartographer]
To github.com:larics/cartographer.git
 ! [remote rejected] HEAD -> ceres-pose-frompose (permission denied)
error: failed to push some refs to 'git@github.com:larics/cartographer.git'
 => Abandoning branch pr_1149.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at ee33d06 Merge branch 'master' into pr_1149
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_1149 [data/cartographer]
Deleted branch pr_1149 (was ee33d06).

~~~

**Pull request merged**
