### PR TITLE
Fix some asan warnings.

### PR DESCRIPTION
**Pull request by gaschler**
Adds a few missing overrides and removes a std::move that
prevented copy elision.

### CODE REVIEW

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 2.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Pull request merged**
