### PR TITLE
Replace CHECK() by a warning in MapBuilderStub::SerializeState()

### PR DESCRIPTION
**Pull request by MichaelGrupp**
See discussion in https://github.com/googlecartographer/cartographer_ros/pull/966

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
@cschuet

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by MichaelGrupp** [comment]
Sorry, had a typo. Might need to trigger Wally again.

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by MichaelGrupp** [comment]
I didn't see a stupid typo - see #1365.

**Pull request merged**
