### PR TITLE
Do not install gmock

### PR DESCRIPTION
**Pull request by gaschler**
Fixes the issue described in https://github.com/googlecartographer/cartographer/pull/1041.

The docker file is not to be merged, it is only here to help reproducing the issue and fix.

### CODE REVIEW

**Comment by gaschler** [comment]
Verified also for cartographer_ros' Indigo docker image.

**Comment by mikaelarguedas** [comment]
This fixes the issue for me :+1: 
Tested on Ubuntu Bionic and Debian Stretch

**Comment by gaschler** [comment]
To reproduce, use the docker file from the previous commit https://github.com/gaschler/cartographer/blob/7de7c8717f3a704d8a197095188bb89a21ec5057/Docker.reproduce

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 2.

**Pull request merged**
