### PR TITLE
Move tools/bazel.rc to prepare for bazel 0.17

### PR DESCRIPTION
**Pull request by drigz**
Bazel 0.17 will no longer import the legacy "tools/bazel.rc" config
file. This change ensures compatibility with the new versions.

For users on bazel 0.16 and earlier who have a ~/.bazelrc, this change
will cause bazel to ignore their ~/.bazelrc and load this one instead.
Hopefully this won't break anyone. (famous last words)

### CODE REVIEW

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by drigz** [comment]
I've updated the rules_boost change to (hopefully) fix the bzip issue too. https://github.com/nelhage/rules_boost/pull/81/files

**Pull request merged**
