### PR TITLE
Add Cartographer high level structure diagram

### PR DESCRIPTION
**Pull request by zjwoody**
I'm thinking maybe add a shared doc is better than pdf, so that everybody can update the diagram for the new changes.

### CODE REVIEW

**Comment by jihoonl** [comment]
I agree with you that an image file or shared doc is better than pdf.

Odometry is also used in optimization problem since #456 is merged.

**Comment by zjwoody** [comment]
Thanks @cschuet ! Could you please merge this pr, because I don't have the write access to this repository. Thanks:)

**Comment by jihoonl** [comment]
I think the embedded image would be better than the link. How do you think

**Comment by zjwoody** [comment]
Done. Thanks for the review!

**Pull request merged**
