### PR TITLE
Fix regression in Protobuf find_package logic.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
The introduced changes are not compatible with CMake < 3.6 if the
FindProtobuf.cmake bundled with CMake is used.
Since our minimum required version is 3.2, I consider this to be a bug.
Issues reported in #1481 are probably related.

- camel-case variables names weren't used before 3.6
  (upper-case is lowered in CMake > 3.6 for backwards compatibility)
- the `CONFIG` search added for the Windows build logs a warning even if the
`REQUIRED` search succeeds, should be quiet

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
https://cmake.org/cmake/help/v3.2/module/FindProtobuf.html

Backwards compatibility: https://github.com/Kitware/CMake/commit/a7b09e7f43fda0a459145053653a614330bf1fe1#diff-a77489da88045e361833b7dfe293c07fR215

I guess the CI pipeline didn't complain because it probably doesn't use the CMake-bundled file.

**Comment by MichaelGrupp** [comment]
Bazel build fails (also on master) because of some unrelated problems.

**Comment by ojura** [comment]
Sorry about that!

**Comment by ojura** [comment]
Windows build is also happy: https://dev.azure.com/larics/cartographer/_build/results?buildId=194

It looks like I wrongly concluded that we need to switch to the camelcase variable to use Protobuf in config mode.

**Comment by mrgransky** [comment]
You may have a look at [here](https://github.com/googlecartographer/cartographer/issues/1481#issuecomment-568904908)!

**Pull request merged**
