### PR TITLE
Add 2D trajectory builder option to accept initial pose estimation

### PR DESCRIPTION
**Pull request by aochiai**
This PR add an option to `mapping_2d::LocalTrajectoryBuilder` to accept initial pose estimation.
User can provide initial pose estimation when they start a new trajectory.

### CODE REVIEW

**Comment by wohe** [comment]
Can you elaborate a bit on the aim of this PR?

As it is right now, it seems there is no need to add this to Cartographer. In the single trajectory case, you could just transform the poses outside of Cartographer itself. If there are multiple trajectories, you'd check the connectivity to determine whether you'd want to transform them.

Most importantly, the proposed change does not properly influence results, e.g. like one would want if there is already knowledge about where to start related to an already existing trajectory.

**Comment by aochiai** [comment]
This PR aims multi trajectory cases.
The motivation of this PR is:
1. I'd like to use a map before it is well optimized to navigate robots if I can provide a appropriate initial estimation.
2. Sometimes it's useful to adjust initial coordinate of a entire map by giving initial estimation to the first trajectory. (e.g. To build a map with the coordinate same as former maps but need to change start point)

> Most importantly, the proposed change does not properly influence results, e.g. like one would want if there is already knowledge about where to start related to an already existing trajectory.

I expected this scenario and tested in such situation. It seems to work well in that case.
Can you tell me a little more detail why do you think this doesn't properly work?

**Comment by wohe** [comment]
Can you elaborate more about your use cases.

1. If you are only interested in changing the coordinate system, this could obviously be done on the outside, i.e. why is just transforming the output not sufficient for your use case?

2. This change does not influence loop closures because it does not change `trajectory_connectivity_` in SparsePoseGraph. See also #329.

3. It seems to me the feature you want should be added on the pose graph level, not the local trajectory builder. The reason for that is that conceptually the poses in the local trajectory builder track the relative changes without loop closure. The optimized poses in the pose graph can differ a lot. Your change sets the local pose to an initial estimate in the map frame of the pose graph. Since the pose graph does not know about this it will still treat the initial pose as arbitrary and do global loop closure matches against all other submaps.

**Comment by SirVer** [comment]
@aochiai What is the status of this PR?

**Comment by wohe** [comment]
Closing this for now, please re-open if you disagree.

**Comment by aochiai** [comment]
Thank you for reviewing and comments.
I will revise my PR.

**Pull request closed without merging**
