### PR TITLE
[ABSL] Purge common::make_unique.

### PR DESCRIPTION
**Pull request by pifon2a**

### CODE REVIEW

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> handle work item: PR 1340 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at 4990d4d5 [ABSL] Purge common::optional. (#1339)
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.

~~~

**Comment by ojura** [comment]
Have you reintroduced optional.h by mistake in this PR?

**Comment by pifon2a** [comment]
@ojura yeah, that I could have done. https://github.com/googlecartographer/cartographer/pull/1349

**Pull request merged**
