### PR TITLE
Synchronize correctly in FinishTrajectory().

### PR DESCRIPTION
**Pull request by wohe**
PoseGraph{2D,3D}::FinishTrajectory() calls AddWorkItem() which
requires the mutex to be held. This adds code to do this.

### CODE REVIEW

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wohe** [comment]
@pifon2a Seems Wally is asleep.

**Comment by wohe** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user wohe. Merge queue now has a length of 1.

**Pull request merged**
