### PR TITLE
Check for collated_fixed_frame_ for AddSensorData(FixedFramePoseData).

### PR DESCRIPTION
**Pull request by CodeArno**
PR #1224 introduced checks for `collate_landmarks` and `collate_fixed_frame` in the `CollatedTrajectoryBuilder`. However, it falsely checks for `collate_landmarks` in the `AddSensorData(FixedFramePoseData)` function. This PR fixes that.

### CODE REVIEW

**Comment by CodeArno** [comment]
@pifon2a @wohe PTAL

**Comment by CodeArno** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user CodeArno. Merge queue now has a length of 2.

**Comment by damienrg** [comment]
Could you add that it fix #1281?

**Comment by MichaelGrupp** [comment]
@CodeArno your pull request was blocked by the Bazel build pipeline, which requires a manual verification. I unblocked it for you.

**Comment by MichaelGrupp** [comment]
Maybe it makes sense to let wally do this trigger, if there's some API from buildkite to do that programatically? IMO "@wally merge..." is already a verification, so that extra button to press is a bit redundant and blocks the merge queue often.

**Pull request merged**
