### PR TITLE
Move GetTrajectoryData() down to PoseGraphInterface

### PR DESCRIPTION
**Pull request by danielsievers**
That way it is accessible to clients of PoseGraph, for example,
if you create a MapBuilder and want to extract reference information
for fixed frame poses.

### CODE REVIEW

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> handle work item: PR 932 on googlecartographer/cartographer.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at ed35029 Add yesterday's slides. (#931)
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer]
From https://github.com/googlecartographer/cartographer
   ed35029..258aa71  master     -> origin/master
Updating ed35029..258aa71
Fast-forward
 cartographer/mapping/pose_graph.h            | 3 ---
 cartographer/mapping/pose_graph_interface.h  | 3 +++
 cartographer_grpc/mapping/pose_graph_stub.cc | 5 +++++
 cartographer_grpc/mapping/pose_graph_stub.h  | 2 ++
 cartographer_grpc/testing/mock_pose_graph.h  | 4 ++++
 5 files changed, 14 insertions(+), 3 deletions(-)
 => Checking out danielsievers/pose_graph_interface as local branch pr_932.
 $ git remote add danielsievers git@github.com:danielsievers/cartographer.git [data/cartographer]
fatal: remote danielsievers already exists.
 $ git fetch danielsievers [data/cartographer]
 $ git branch --track pr_932 danielsievers/pose_graph_interface [data/cartographer]
Branch 'pr_932' set up to track remote branch 'pose_graph_interface' from 'danielsievers'.
 => Switching to branch pr_932.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at 258aa71 Move GetTrajectoryData() down to PoseGraphInterface (#932)
 $ git clean -fd [data/cartographer]
 $ git checkout pr_932 [data/cartographer]
Switched to branch 'pr_932'
Your branch is up to date with 'danielsievers/pose_graph_interface'.
 $ git pull --force [data/cartographer]
Already up to date.
 => merge master.
 $ git merge master [data/cartographer]
Merge made by the 'recursive' strategy.
 => Running clang-format on all *.cc and *.h files
 $ git commit -am Ran clang-format. [data/cartographer]
On branch pr_932
Your branch is ahead of 'danielsievers/pose_graph_interface' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
 $ git push --force danielsievers HEAD:pose_graph_interface [data/cartographer]
To github.com:danielsievers/cartographer.git
 ! [remote rejected] HEAD -> pose_graph_interface (permission denied)
error: failed to push some refs to 'git@github.com:danielsievers/cartographer.git'
 => Abandoning branch pr_932.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer]
HEAD is now at 447d4c6 Merge branch 'master' into pr_932
 $ git clean -fd [data/cartographer]
 $ git checkout master [data/cartographer]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_932 [data/cartographer]
Deleted branch pr_932 (was 447d4c6).

~~~

**Pull request merged**
