### PR TITLE
fix warning about struct being redefined as class

### PR DESCRIPTION
**Pull request by wjwwood**
This fixes a warning I get on macOS using clang:

```
[  6%] Building CXX object CMakeFiles/cartographer.dir/cartographer/mapping/collated_trajectory_builder.cc.o
In file included from /Users/william/ros2_ws/src/vendor/cartographer/cartographer/mapping/collated_trajectory_builder.cc:17:
In file included from /Users/william/ros2_ws/src/vendor/cartographer/cartographer/mapping/collated_trajectory_builder.h:28:
In file included from /Users/william/ros2_ws/src/vendor/cartographer/cartographer/mapping/global_trajectory_builder_interface.h:25:
/Users/william/ros2_ws/src/vendor/cartographer/cartographer/mapping/submaps.h:95:1: warning: 'Submaps' defined as a class here but previously declared as a struct [-Wmismatched-tags]
class Submaps {
^
/Users/william/ros2_ws/src/vendor/cartographer/cartographer/mapping/trajectory_node.h:32:1: note: did you mean class here?
struct Submaps;
^~~~~~
class
1 warning generated.
```

### CODE REVIEW

**Comment by wjwwood** [comment]
I signed it!

@damonkohler this was working last week, any idea why it's not happy now?

**Comment by damonkohler** [comment]
I signed it!

**Comment by damonkohler** [comment]
Looks like it might be confused. Try commenting:

I signed it! Open Source Robotics Foundation, Inc.

**Comment by SirVer** [comment]
@wjwwood William, GitHub does not associate your email used for the commit with your GitHub account. Maybe if you fix this, CLA bot will not be confused. You can see the issue [here](https://github.com/googlecartographer/cartographer/pull/228/commits/2b2bcc645be685b503e7187a04a31ff8d4f4fd21). 

Just to clarify: We could override CLA bot and merge this manually right now, but we assume that you will want to continue contributing so we'd rather remove the root cause of this issue once.

**Comment by wjwwood** [comment]
I had added a `+github` into my email, so I guess that's why it didn't connect the dots. Let's try again.

I signed it! Open Source Robotics Foundation, Inc.

**Comment by wjwwood** [comment]
Do you need me to rebase this? The two new merge commits look strange to me.

**Comment by damonkohler** [comment]
Sorry, this fell off my radar yesterday. I've been trying to figure out why Travis isn't flipping the status check properly.

No need to rebase. We'll do a squash and merge anyway.

**Pull request merged**
