### PR TITLE
Do not use operator*= with Jets.

### PR DESCRIPTION
**Pull request by pifon2a**
Should fix https://github.com/googlecartographer/cartographer/issues/1015.

Jets in Ceres do not have an overloaded `operator*=` that can work with scalars.

### CODE REVIEW

**Comment by ojura** [comment]
Why not bump up the Ceres version?

**Comment by pifon2a** [comment]
Ceres 1.13 is already used in all our Docker files and it does not solve the problem. I will file a bug to Ceres folks to add the operator. In the meantime, this fix will do.

**Comment by ojura** [comment]
Ah, okay. [As you noticed](https://github.com/googlecartographer/cartographer/issues/1015#issuecomment-375585331), how did it manage to pass CI earlier when we merged #1000 and #998?

**Comment by pifon2a** [comment]
Our CI use different dockerfiles (do not ask me why :) )

**Pull request merged**
