### PR TITLE
Nit: use current year and no hardcoded version in Sphinx docs.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
`Cartographer 1.0.0 documentation` -> `Cartographer documentation`
`Copyright 2016 The Cartographer Authors` -> `Copyright <year> The Cartographer Authors`

### CODE REVIEW

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by MichaelGrupp** [comment]
@wally-the-cartographer ?

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Comment by MichaelGrupp** [comment]
Wally is on vacation?

**Pull request merged**
